// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOS():Promise<string>;

export function GetTorIP():Promise<string>;

export function StartTor():Promise<string>;
