// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetTorIP() {
  return window['go']['main']['App']['GetTorIP']();
}

export function StartTor() {
  return window['go']['main']['App']['StartTor']();
}
