// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIP():Promise<string>;

export function GetPing():Promise<number>;

export function StartTor():Promise<string>;

export function StopTor():Promise<string>;
