// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeIP() {
  return window['go']['main']['App']['ChangeIP']();
}

export function CheckIP() {
  return window['go']['main']['App']['CheckIP']();
}

export function GetPing() {
  return window['go']['main']['App']['GetPing']();
}

export function StartTor() {
  return window['go']['main']['App']['StartTor']();
}

export function StopTor() {
  return window['go']['main']['App']['StopTor']();
}
